### ISSUE TITLE
魚にUniqueNameとDynamicDataをつける

### ISSUE THREAD

**Issue by ghost** [GrassLife/GrassGathering#4]
### 理由
* 料理で魚を調理する際、魚を素材として認識する必要がある

### つけてほしいもの
* UniqueName (String / Jsonを呼び込む際必須)
* ExpireDate (String / 消費期限、LocalDateTime#toString()を用いる)
* FoodElement/SACHI (int / 海の幸度 0~-5までの値で指定 絶対値が大きくなるほど度合が高い)
* Calorie (String("*0.98"のような感じに) / Jsonに記入された標準のカロリーを指定された倍する)
* Weight (String(Calorieと同様) / Jsonに記入された標準の重さを指定された倍する)

**Comment by cyclic-ester** [comment]
済
